### ISSUE TITLE
Running without concurrency flag gives error and no output even if do use it

### ISSUE THREAD

**Issue by tim-peterson** [bighappyworld/email-verify#25]
I'm encountering two issues.

1. When I don't use the `-c` concurrency flag, I get an error related to it being `undefined`.

```
timrpeterson$ email-verify tim@mydomain.com
Unhandled rejection TypeError: 'concurrency' must be a number but it is [object Undefined]
    at map (/usr/local/lib/node_modules/email-verify/node_modules/bluebird/js/release/map.js:140:21)
    at Function.Promise.map (/usr/local/lib/node_modules/email-verify/node_modules/bluebird/js/release/map.js:160:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/email-verify/app.js:112:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

2.  Unfortunately when I add in the flag, the script hangs and never produces output:

```
timrpeterson$ email-verify tim@mydomain.com -c 1

(never any output)
```

Thoughts?

**Comment by bighappyworld** [comment]
This is a bug. Thanks for letting me know about this. Will push a new version soon. I saw if you pass the -c option it works as you described.

**Comment by bighappyworld** [comment]
should be corrected
