### ISSUE TITLE
Always timing out

### ISSUE THREAD

**Issue by shivkanthb** [bighappyworld/email-verify#35]
{ Error: connect ETIMEDOUT 66.96.140.72:25
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '66.96.140.72',
  port: 25 }

any reason on why this might be happening?

**Comment by bighappyworld** [comment]
Many reasons can cause this. Most likely lack of connectivity to the host. Could be a poor DNS, could be a firewall... but it is very unlikely to be the library as this is just a straight TCP connection with nothing fancy.

**Comment by bhaumikdarji** [comment]
Hi,
Also got always time out.  any reason?
{ Error: connect ETIMEDOUT 66.96.140.72:25
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
code: 'ETIMEDOUT',
errno: 'ETIMEDOUT',
syscall: 'connect',
address: '66.96.140.72',
port: 25 }

**Comment by fizerkhan** [comment]
I too got this issue. Any other settings in Linux could solve this issue?
